### ISSUE TITLE
draft design for dataset(package) view

### ISSUE THREAD

**Issue by saylorsd** [WPRDC/ckanext-wprdctheme#2]
e.g.: https://data.wprdc.org/dataset/allegheny-county-covid-19-vaccinations

Considerations:
- what to list with resources
- metadata and where it goes (maybe some fields should be promoted to other parts of the layout - besides the metadata table)
- description area
- special types of content
  - dataset-specific warnings
  - freshness badges
  - different types of badges

**Comment by saylorsd** [comment]
ETL info to show with badges or something.
- green badge for ETL that's working as intended.
- badges for stale or something.
- bunches of levels of ganularity
like an ETL status badge

**Comment by drw** [comment]
On pipeline status badges for individual resources (to be shown inline with the resources in the package view): I can think of two failure modes that should be incorporated in the status:

1. Is the source data available and fresh (based on the file timestamp)? (We're currently hashing some source files and storing the hash and a last-hashed timestamp in package metadata. rocket-etl jobs check the hash as a post-processing step and Slacks us if the file is stale, so this is one general-purpose way to check source freshness.

2. Did the ETL job run? (rocket-etl stores the datetime.now() in the last_etl_update extras metadata field after each successful run.

(We've previously been asking "Is the data itself updating?" by looking at datetime fields in the data, and this is the whole basis of the pocket-watch tool and the stale-datasets Slack channel, but this approach has problems, and I think checking whether the hash of the source file is changing is the way to go.)

So for each resource: 1) If it's powered by a repeating ETL job, it seems like it could benefit from two tiny badges. One for source-file status and one for overall pipeline status (so if the source file is missing or stale, both would show bad statuses, even if our ETL jobs is still working). It could be like a source badge and an overall badge (each of which can either be "Passing" or "Failing"). 2) If it's not fed by a repeating ETL job, it could just have one badge marking it as a manual upload.

(One idea I had is that the shape of the badges could suggest the dependency between them. Maybe like wide chevrons that fit together and point to the right.)

How to distinguish between static and updating manually uploaded resources? We might have to tag them (with more package-level metadata). Similarly, if we want to put update frequencies on them (different from whatever the default is for the dataset), we'd have to do that manually too. (The update frequency for a resource updated by an ETL job could be coded into the ETL job.)

We'll have to train people to stop looking at the metadata_modified metadata field.
